version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.10
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DATABASE_URL: $DATABASE_URL
      DEBUG: $DEBUG
      GROQ_API_KEY: $GROQ_API_KEY

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            source venv/bin/activate
            python -m pytest base/tests/ --nomigrations -v

  build-and-push:
    docker:
      - image: circleci/python:3.9
    environment:
      GROQ_API_KEY: $GROQ_API_KEY
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Print Docker Tag
          command: echo "Building Docker image $DOCKERHUB_USERNAME/study-buddy:latest"
      - run:
          name: Build Docker Image
          command: |
            docker build \
              --build-arg GROQ_API_KEY=$GROQ_API_KEY \
              -t $DOCKERHUB_USERNAME/study-buddy:latest .
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Image to DockerHub
          command: |
            docker push $DOCKERHUB_USERNAME/study-buddy:latest


workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
