version: 2.1

parameters:
  GROQ_API_KEY:
    type: string
    default: ""

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    environment:
      GROQ_API_KEY: $GROQ_API_KEY

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            source venv/bin/activate
            python -m pytest base/tests/ --nomigrations -v

  build-and-push:
    executor: python-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            echo "Building Docker image..."
            docker build --build-arg GROQ_API_KEY=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 -t $DOCKERHUB_USERNAME/study-buddy:latest .
            echo "Docker build completed"
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Image to DockerHub
          command: |
            docker push $DOCKERHUB_USERNAME/study-buddy:latest

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
